version: "2"

linters:
  # errcheck, govet, ineffassign, staticcheck, unused
  default: standard
  enable:
    - nolintlint
  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/swat9013/sbxr
